version: "3.8"

services:
  cloud-mosquitto-broker:
    container_name: cloud-mosquitto-broker
    image: eclipse-mosquitto:2.0.12
    ports:
      - "1884:1883"
    volumes:
      - ./mosquitto_cloud.conf:/mosquitto/config/mosquitto.conf
    restart: always
    networks:
      - iot_production_line_network

  http-api:
    container_name: http-api
    image: http-api:0.1
    ports:
      - "7070:7070"
    volumes:
      - ./target_api_conf.yaml:/app/conf.yaml
    restart: always
    networks:
      - iot_production_line_network

  web-ui:
    container_name: web-ui
    image: web-ui:0.1
    ports:
      - "7071:7071"
    volumes:
      - ./target_web_conf.yaml:/app/web_conf.yaml
    restart: always
    depends_on:
      - http-api
    networks:
      - iot_production_line_network

  mqtt_data_fetcher:
    container_name: mqtt_data_fetcher
    image: data-fetcher:0.1
    volumes:
      - ./target_fetcher_conf.yaml:/app/fetcher_conf.yaml
    restart: always
    depends_on:
      - cloud-mosquitto-broker
      - http-api
    networks:
      - iot_production_line_network

  mqtt-fault-actuator:
    container_name: mqtt-fault-actuator
    image: mqtt-fault-actuator:0.1
    volumes:
      - ./target_actuator_conf.yaml:/app/actuator_conf.yaml
    restart: always
    depends_on:
      - cloud-mosquitto-broker
    networks:
      - iot_production_line_network

networks:
  iot_production_line_network:
    driver: bridge
